module.exports =  {
  log: ['white', 'color: black'],
  none: ['white', 'color: black'],
  debug: ['magenta', 'color: magenta'],
  info: ['blue', 'color: blue'],
  success: ['green', 'color: green'],
  hint: ['yellow', 'color: orange'],
  warn: ['yellow', 'color: brown'],
  warning: ['yellow', 'color: brown'],
  error: ['red', 'color: red'],
  quit: ['red', 'color: red'],
  GET: ['bold_green', 'color: green; font-weight: bold'],
  POST: ['bold_yellow', 'color: orange; font-weight: bold'],
  PUT: ['bold_blue', 'color: blue; font-weight: bold'],
  DELETE: ['bold_red', 'color: red; font-weight: bold'],
  OPTIONS: ['bold_cyan', 'color: cyan; font-weight: bold'],
}
